---
services:
  postgres:
    image: postgres:12.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=website
    volumes:
      - ial-website-data:/var/lib/postgresql/data

volumes:
  ial-website-data:
